/**
 * seedData - Initial service providers seeded into IndexedDB on first launch.
 *
 * These are real local service providers in Fortaleza/CE so that the app
 * has meaningful content immediately, before any Supabase sync.
 */
import type { ServiceProvider } from '@shared/types';

const now = Date.now();

/**
 * Fixed UUIDs for seed services so they are Supabase-compatible and
 * deterministic across re-installs (prevents duplicates on re-seed).
 */
const SEED_UUIDS: Record<string, string> = {
  'tiago-ar-condicionado': 'f0d2d5b6-5742-4733-be18-c2f5f3fe2063',
  'felipe-eletricista': 'b1023ffc-8d0a-45ad-b431-d4587313f9ce',
  'edmario-chaveiro': 'b95c745c-082f-4b05-88a2-1bdfa7d2374f',
  'antonio-bombeiro-hidraulico': 'f7e4b9a8-8ff0-4bfd-8a84-b2d1b0183983',
  'drogaria-ceara': '4763df3d-d259-4916-9386-ad147970fc46',
  'francisco-jardineiro': 'e35a5de9-c8f4-4636-ba97-3667c2193fd3',
  'sonia-costureira': '2b80143a-94ec-4035-90ef-47fc76492550',
  'lacarte-marmitaria': '01034e6d-505f-462b-a2ec-d528f827fdbd',
};

function seedId(slug: string): string {
  return SEED_UUIDS[slug] ?? crypto.randomUUID();
}

export const SEED_SERVICES: ServiceProvider[] = [
  {
    id: seedId('tiago-ar-condicionado'),
    name: 'Tiago F.A Ar Condicionado',
    description:
      'Instalação, manutenção e limpeza de ar condicionado split e de janela. Atendimento residencial e comercial em Fortaleza e região metropolitana.',
    category: 'outros',
    subcategory: 'tecnico_ar',
    phone: '(85) 98142-5401',
    hasWhatsApp: true,
    whatsAppConfirmed: true,
    address: 'Fortaleza, CE',
    location: { latitude: -3.7172, longitude: -38.5433, accuracy: 50, timestamp: now },
    averageRating: 0,
    totalRatings: 0,
    recentRatings: [],
    registeredBy: 'system',
    neighborhoodScore: 0,
    dataSource: 'manual',
    verifiedByUsers: 0,
    createdAt: now,
    updatedAt: now,
    isActive: true,
  },
  {
    id: seedId('felipe-eletricista'),
    name: 'Felipe Eletricista',
    description:
      'Serviços de instalação e manutenção elétrica residencial e predial. Troca de fiação, disjuntores, tomadas, chuveiros e quadros de força.',
    category: 'reparos_domesticos',
    subcategory: 'eletricista',
    phone: '(85) 81729-135',
    hasWhatsApp: true,
    whatsAppConfirmed: true,
    address: 'Fortaleza, CE',
    location: { latitude: -3.7327, longitude: -38.5267, accuracy: 50, timestamp: now },
    averageRating: 0,
    totalRatings: 0,
    recentRatings: [],
    registeredBy: 'system',
    neighborhoodScore: 0,
    dataSource: 'manual',
    verifiedByUsers: 0,
    createdAt: now,
    updatedAt: now,
    isActive: true,
  },
  {
    id: seedId('edmario-chaveiro'),
    name: 'Edmário Chaveiro',
    description:
      'Abertura de portas, troca de fechaduras, cópias de chaves, instalação de trancas e cadeados. Atendimento 24h em Fortaleza.',
    category: 'reparos_domesticos',
    subcategory: 'chaveiro',
    phone: '(85) 96182-047',
    hasWhatsApp: true,
    whatsAppConfirmed: true,
    address: 'Fortaleza, CE',
    location: { latitude: -3.74, longitude: -38.51, accuracy: 50, timestamp: now },
    averageRating: 0,
    totalRatings: 0,
    recentRatings: [],
    registeredBy: 'system',
    neighborhoodScore: 0,
    dataSource: 'manual',
    verifiedByUsers: 0,
    createdAt: now,
    updatedAt: now,
    isActive: true,
  },
  {
    id: seedId('antonio-bombeiro-hidraulico'),
    name: 'Antonio Oliveira - Bombeiro Hidráulico',
    description:
      'Reparos hidráulicos, desentupimentos, conserto de vazamentos, instalação de torneiras, caixas d\'água e tubulações em geral.',
    category: 'reparos_domesticos',
    subcategory: 'encanador',
    phone: '(85) 9138-4289',
    hasWhatsApp: true,
    whatsAppConfirmed: true,
    address: 'Fortaleza, CE',
    location: { latitude: -3.75, longitude: -38.53, accuracy: 50, timestamp: now },
    averageRating: 0,
    totalRatings: 0,
    recentRatings: [],
    registeredBy: 'system',
    neighborhoodScore: 0,
    dataSource: 'manual',
    verifiedByUsers: 0,
    createdAt: now,
    updatedAt: now,
    isActive: true,
  },
  {
    id: seedId('drogaria-ceara'),
    name: 'Drogaria Ceará',
    description:
      'Farmácia e drogaria com entrega em domicílio. Medicamentos, produtos de higiene e perfumaria.',
    category: 'outros',
    phone: '(85) 99999-9999',
    hasWhatsApp: true,
    whatsAppConfirmed: true,
    address: 'Fortaleza, CE',
    location: { latitude: -3.725, longitude: -38.54, accuracy: 50, timestamp: now },
    averageRating: 0,
    totalRatings: 0,
    recentRatings: [],
    registeredBy: 'system',
    neighborhoodScore: 0,
    dataSource: 'manual',
    verifiedByUsers: 0,
    createdAt: now,
    updatedAt: now,
    isActive: true,
  },
  {
    id: seedId('francisco-jardineiro'),
    name: 'Francisco Jardineiro',
    description:
      'Serviços de jardinagem, poda de árvores, corte de grama, limpeza de terreno, plantio e manutenção de jardins residenciais e comerciais.',
    category: 'outros',
    subcategory: 'jardineiro',
    phone: '(85) 99402-1416',
    hasWhatsApp: true,
    whatsAppConfirmed: true,
    address: 'Fortaleza, CE',
    location: { latitude: -3.735, longitude: -38.55, accuracy: 50, timestamp: now },
    averageRating: 0,
    totalRatings: 0,
    recentRatings: [],
    registeredBy: 'system',
    neighborhoodScore: 0,
    dataSource: 'manual',
    verifiedByUsers: 0,
    createdAt: now,
    updatedAt: now,
    isActive: true,
  },
  {
    id: seedId('sonia-costureira'),
    name: 'Sonia Mota Costureira',
    description:
      'Costura, ajustes de roupas, bainhas, consertos, customização e pequenos reparos em vestuário. Atendimento com qualidade e pontualidade.',
    category: 'servicos_pessoais',
    subcategory: 'costureira',
    phone: '(85) 98100-4868',
    hasWhatsApp: true,
    whatsAppConfirmed: true,
    address: 'Fortaleza, CE',
    location: { latitude: -3.728, longitude: -38.535, accuracy: 50, timestamp: now },
    averageRating: 0,
    totalRatings: 0,
    recentRatings: [],
    registeredBy: 'system',
    neighborhoodScore: 0,
    dataSource: 'manual',
    verifiedByUsers: 0,
    createdAt: now,
    updatedAt: now,
    isActive: true,
  },
  {
    id: seedId('lacarte-marmitaria'),
    name: 'Lacarte Marmitaria',
    description:
      'Marmitas e refeições variadas para almoço e jantar, com opções do dia. Entregas na região de Fortaleza.',
    category: 'outros',
    phone: '(85) 99216-5444',
    hasWhatsApp: true,
    whatsAppConfirmed: true,
    address: 'Fortaleza, CE',
    location: { latitude: -3.72, longitude: -38.545, accuracy: 50, timestamp: now },
    averageRating: 0,
    totalRatings: 0,
    recentRatings: [],
    registeredBy: 'system',
    neighborhoodScore: 0,
    dataSource: 'manual',
    verifiedByUsers: 0,
    createdAt: now,
    updatedAt: now,
    isActive: true,
  },
];
