/**
 * Property 8: Brazilian Phone Number Validation
 *
 * For any input string, the phone validation function must accept only
 * strings matching valid Brazilian phone formats (with or without area code,
 * with or without country code), and reject all other strings.
 *
 * **Validates: Requirements 4.4**
 */
import { describe, it, expect } from 'vitest';
import * as fc from 'fast-check';
import { isValidBrazilianPhone } from '@shared/utils/validation';
import { brazilianPhoneArb, propertyTestConfig } from './generators';

/** Helper to generate a digit string of exact length */
const digitString = (length: number): fc.Arbitrary<string> =>
  fc.array(fc.constantFrom('0', '1', '2', '3', '4', '5', '6', '7', '8', '9'), {
    minLength: length,
    maxLength: length,
  }).map((digits) => digits.join(''));

describe('Property 8: Brazilian Phone Number Validation', () => {
  /**
   * **Validates: Requirements 4.4**
   *
   * All phone numbers produced by the brazilianPhoneArb generator
   * must be accepted by isValidBrazilianPhone.
   */
  it('should accept all valid Brazilian phone numbers generated by brazilianPhoneArb', () => {
    fc.assert(
      fc.property(brazilianPhoneArb, (phone) => {
        expect(isValidBrazilianPhone(phone)).toBe(true);
      }),
      propertyTestConfig,
    );
  });

  /**
   * **Validates: Requirements 4.4**
   *
   * Random arbitrary strings that do not match any valid Brazilian phone
   * pattern should be rejected by isValidBrazilianPhone.
   */
  it('should reject random strings that are not valid phone numbers', () => {
    fc.assert(
      fc.property(
        fc.string().filter((s) => {
          // Filter out strings that accidentally match valid phone formats
          return !/^\(?\+?\d/.test(s) || s.length < 5;
        }),
        (randomStr) => {
          expect(isValidBrazilianPhone(randomStr)).toBe(false);
        },
      ),
      propertyTestConfig,
    );
  });

  /**
   * **Validates: Requirements 4.4**
   *
   * Edge cases: empty string, very short strings, and very long strings
   * must all be rejected.
   */
  it('should reject empty strings, too-short strings, and too-long strings', () => {
    fc.assert(
      fc.property(
        fc.oneof(
          fc.constant(''),
          fc.string({ maxLength: 7 }),
          fc.string({ minLength: 25, maxLength: 100 }),
        ),
        (input) => {
          // Strings that are too short or too long cannot be valid phones
          if (input.length <= 7 || input.length >= 25) {
            expect(isValidBrazilianPhone(input)).toBe(false);
          }
        },
      ),
      propertyTestConfig,
    );
  });

  /**
   * **Validates: Requirements 4.4**
   *
   * Phone numbers with invalid DDD codes (not in the official list)
   * must be rejected when DDD is present.
   */
  it('should reject phone numbers with invalid DDD codes', () => {
    const invalidDdds = ['00', '01', '10', '20', '23', '25', '26', '29',
      '30', '36', '39', '40', '50', '52', '56', '57', '58', '59',
      '60', '70', '72', '76', '78', '80', '90'];

    fc.assert(
      fc.property(
        fc.constantFrom(...invalidDdds),
        fc.oneof(
          // Mobile number (9 digits starting with 9)
          digitString(8).map((rest) => '9' + rest),
          // Landline number (8 digits)
          digitString(8),
        ),
        (ddd, number) => {
          const withParens = `(${ddd}) ${number.slice(0, number.length === 9 ? 5 : 4)}-${number.slice(number.length === 9 ? 5 : 4)}`;
          const withCountry = `+55 ${ddd} ${number.slice(0, number.length === 9 ? 5 : 4)}-${number.slice(number.length === 9 ? 5 : 4)}`;

          expect(isValidBrazilianPhone(withParens)).toBe(false);
          expect(isValidBrazilianPhone(withCountry)).toBe(false);
        },
      ),
      propertyTestConfig,
    );
  });
});


/**
 * Property 11: Comment Length Validation
 *
 * For any comment string with more than 500 characters, the system must reject
 * the submission. For strings with 500 characters or less, the comment must be accepted.
 *
 * **Validates: Requirements 5.3**
 */
import { isValidComment } from '@shared/utils/validation';

describe('Property 11: Comment Length Validation', () => {
  /**
   * **Validates: Requirements 5.3**
   *
   * Any string with length <= 500 must be accepted.
   */
  it('should accept any comment with length <= 500 characters', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 0, maxLength: 500 }),
        (comment) => {
          expect(isValidComment(comment)).toBe(true);
        },
      ),
      propertyTestConfig,
    );
  });

  /**
   * **Validates: Requirements 5.3**
   *
   * Any string with length > 500 must be rejected.
   */
  it('should reject any comment with length > 500 characters', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 501, maxLength: 2000 }),
        (comment) => {
          expect(isValidComment(comment)).toBe(false);
        },
      ),
      propertyTestConfig,
    );
  });

  /**
   * **Validates: Requirements 5.3**
   *
   * Boundary: exactly 500 characters is accepted, 501 is rejected.
   */
  it('should accept exactly 500 characters and reject 501 characters', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 500, maxLength: 500 }),
        (base500) => {
          // Exactly 500 must be accepted
          expect(isValidComment(base500)).toBe(true);
          // Adding one more character must be rejected
          expect(isValidComment(base500 + 'x')).toBe(false);
        },
      ),
      propertyTestConfig,
    );
  });

  /**
   * **Validates: Requirements 5.3**
   *
   * Undefined comments are accepted (comments are optional).
   */
  it('should accept undefined comments (optional field)', () => {
    expect(isValidComment(undefined)).toBe(true);
  });
});
